version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: user-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photomanager
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: photo-manager-redis
    ports:
      - "6379:6379"

  gateway:
    image: nginx:alpine
    container_name: photo-manager-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  front:
    build: ./modules/front
    container_name: photo-manager-front
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - photo-service

  user-service:
    build: ./modules/user-service
    container_name: photo-manager-user-service
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/photomanager
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

  photo-service:
    build: ./modules/photo-service
    container_name: photo-manager-photo-service
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/photomanager
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
