services:
  postgres-db:
    image: postgres:15-alpine
    container_name: photo-manager-postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: user_service_db,photo_service_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: photo-manager-redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    container_name: photo-manager-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: ""

  gateway:
    image: nginx:alpine
    container_name: photo-manager-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
